const articles = [
  {
    name: 'about',
    title: 'Cute Blog React',
    date: '14 april 2022',
    desc: 'about cute blog for react js',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    content: [
      `This is a blogger platform develope and build using react framework for simple and modern blog.
      New Generation Simple way to blogs with react js, blast fast blogs.`,
      `Saat nya kini update blog kamu dengan ngeblog pakai react, kenapa sih react , ya soalnya cepet aja fast load jadi kesengsem, ini open source code blog develope makai react js, mayan lah buat belajar yess... `,
      `Sensasi dengan menggunakan react untuk ngeblog adalah tentu kecepatan nya gengs, super duper cepat lah,, lebih slim dan ringan lagi , dan ini merupakan populer framework dunia yang dipersembahkan oleh team dev facebook untuk developer dunia , bekerja dengan react sangat mengasyikan,yuk tes dan buat bangun blog modern kamu dengan react apps.`,
    ],
  },
  {
    name: 'gatsby-js',
    title: 'Gatsby JS',
    desc: 'Gatsby with react JS',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://media.istockphoto.com/vectors/business-communication-internet-blogging-post-flat-design-vector-vector-id1143088863?k=20&m=1143088863&s=612x612&w=0&h=kJgOoz9QAhbT83Acyhm9whRtxt2j7J7VzWAxCHuEa8o=',
    content: [
      `Tau kah kamu, static site generator gatsby js juga makai react loh,, yap gatsby menjelma menjadi populer karena kemudahan nya dalam develpe dan super duper SEO untuk digunakan, berbasis platform react menyempurnakan gatsby merajai dunia statis site generator.`,
      `Kalau kita biasa nya bikin web apalagi berbasis generator static site modern tentu gatsby pilihan utama , karena kecepatan untuk deploy nya, dan ditambah faktor SEO memudahkan kita untuk membangun dengan cepat sebuah project webiste untuk dikembangkan.`,
      `Yuk coba bikin dan bangun site kamu dengan framework react dong biar kekinian dan keren, dan bisa juga makai gatsby kalau kamu pengen ngerasain keren dan modern nya website atau blog kamu makai react ini.`,
    ],
  },
  {
    name: 'angular',
    title: 'Angular',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    desc: 'Modern Dan elegan website dengan angular',
    content: [
      `Nah yang satu ini bikin puyeng kepala yes.. tingkat kesulitan nya super wow dengan develope project web app dengan angular, tapi setelah proses develope dan deploy selesai rasanya puas dan bangga gitu deh, secara si ng ini memang bener bener bikin kepala hampir botak dan urat nadi mau putus neh.. wwkwk malah curhat yess.`,
      `Membuat dan membangun website apps via angular relatif membutuhkan waktu lebih lama, karena ya ada beberapa proses nya ntu,, belum lagi emang lebih sulit sih , jadi harus bersabar ini ujian....`,
      `Btw waktu project kelar dengan angular rasanya puas gitu deh,, rasa capek ilang uda liat karya kita, wakakaka... mau coba angular ?? why not.. yuk sinau angular sampek botak.`,
    ],
  },
  {
    name: 'laravel',
    title: 'Laravel PHP artisan',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    desc: 'Magican bersama laravel',
    content: [
      `Sang artis dan pendatang baru di dunia framework serta sangat populer di dunia , super magic sih kalau biasa menggunakan PHP , laravel boleh dibilang masih baru loh... awalnya sih banyak orang yang meremahkan framework ini, dan ketika itu masih banyak yg makain CI code iginter dan symfony untuk berbagai project , setelah muncul nya klan js dan ts maka si lara ni tiba tiba ikut muncul juga, dan berkat kehadiran nya klan PHP masih terjaga,dari serangan JS dan TS.`,
      `The Artisan.. yap cukup mempunyai arti seni luar biasa atau art lah yes.. dengan codding berseni ceileh,,, laravel super magic dan relatif lebih mudah dipahami, bahkan kita juga banyak develope project site dan aplikasi makai framewrok ini, ya karena alasan kemudahan nya sih.`,
      `Pengen coba laravel ?? yuk belajar laravel aja yes, be artisan with laravel php artisan.`,
    ],
  },
  {
    name: 'modx',
    title: 'MODX Revolutions',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    desc: 'Revolusi dan evolusi bersama MODX',
    content: [
      `Salah satu content management framework favorit kita juga, laternatif dari wordpress, menggunakan modx sangat luar biasa bebas nya, dan tentunya faktor SEO menyempurnakan nya, dengan MODX lebih leluasa untuk berbagai kebutuhan pekerjaan melakukan apapun itu untuk develope nya.`,
      `Berbasis PHP menjadikan mudah bagi yang suka bermain dengan bahasa php atau menggunakan hosting umum yes, kelebihan menggunakan nya adalah convert langsung ke html , ini alasan saya menyukai nya.`,
      `Pada generasi Old school jaman dulu CMS masih dikuasai oleh wordpress, drupal, dan joomla, hingga modx hadir sebagai pendatang baru dan mendapat sambutan luar biasa oleh para developer dunia karena super terbuka bebas aman dan super cepat dengan menggunakan MODX revolutions ini, makanya dia disebut revolusi, mau belajar MODX , lgsg aja yes kunjungi situs nya.`,
    ],
  },
  {
    name: 'jekyll',
    title: 'Jekyll Ruby on Rails',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    desc: 'Statis site super ringan dengan jekyll',
    content: [
      `Mau sensasi yang lebih keren lagi untuk membangun site atau blog, maka jekyll bisa menjadi pilihan utama mu untuk membuat dan develope modern website maupun blog , dengan jekyll semakin lebih cepat lagi untuk akses speed load nya, dan dengan ruby on rails menyempurnakan jekyll bekerja super cepat nya.`,
      `Menggunakan jekyll juga bisa langsung host ke github pages , semakin mudah untuk develope modern site dan blog mu, kami juga banyak menggunakan jekyll untuk ngeblog dan bahkan salah satu website juga kami bangun menggunakan jekyll, alasan menggunakan nya selain SEO faktor dan tentu saja super duper ringan .`,
      `Mau coba sensasi jekyll ?? yuk pelajari langsung di situs nya yess..`,
    ],
  },
  {
    name: 'blogspot',
    title: 'Blogspot New Age',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    date: '14 april 2022',
    desc: 'Masih setia dengan sih blogger blogspot platform',
    content: [
      `Hayo,, ngaku siapa yang masih setia makai blogspot nih ?? blogger blogspot menjadi populer saat itu bersanding dengan wordpress, ya tentunya sebelum masuk dan bangkitnya para generasi modern yess. dengan blogspot memudahkan segala nya,asalkan mengetahui kodding blogpost dapat dirubah menjadi superior untuk teechnology nya.`,
      `Single page application atau progresive web apps dengan blogspot juga bisa dilakukan dengan insert dan injeksi platform generasi ke tiga untuk bantuan mencapai tujuan itu,saya sendiri sudah menerapkan sih untuk single page application website non loading page to page dengan blogspot juga bisa.`,
      `Merubah tampilan per halaman halaman blogspot, karena tema blogspot yang mudah dicustom menjadikan kemudahan juga untuk build modern website menggunakan blogspot blogger platform ini, so.. jangan tinggalkan kenangan kalian dengan blogspot walau banyak serangan dan muncul nya generasi baru, blogspot super istimewah dengan berbagai kebebasan customise nya.`,
    ],
  },
  {
    name: 'getaxcora',
    title: 'Get Axcora CMS',
    date: '14 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    desc: 'Modern CMS generasi terbaru tanpa database super cepat dan ringan',
    content: [
      `Nah kalau kalian nih kesulitan untuk melakukan installasi dan deploy develope berbagai technology modern framewrok seperti gatsby, react js, angular dan laravel maka cms ini bisa kamu gunakan , solusi paling tepat deh.`,
      `Perkembangan akan kebutuhan untuk simple cms maka terciptanya get axcora cms ini, super ringan dan cepat tanpa database plus seo otomatis title deskripsi facebook twitter card sampai sitemap xml sudah disediakan semua, jadi tinggal pakai saja`,
      `Pada backend nya tersedia login page, trus.. page content untuk halaman konten artikel update info dan lain lain, file manager untuk upload file file kamu disini dan setting untuk konfigurasi website kamu, dan hadir tema tema keren semakin wow punya deh.. pengen nyobain ?? kunjungi langsung situs nya www.axcora.com/getaxcoracms `,
    ],
  },
];

export default articles;
