const articles = [
  {
    name: 'about',
    title: 'Cuteblog React',
    date: '22 april 2022',
    desc: 'about cute blog for react js',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://cdn.dribbble.com/users/77598/screenshots/5919494/dribbble.png',
    content: [
      `Cuteblog for react is designed specially for react js, so with this source code project or free template themes for react make you fast and easy to build modern blogging website using react js and cuteblog.`,
      `Super fast and of course we have injection with auto generated SEO for this project, yes.. we use helmet !!`,
      `With this concept so you can just focusing on your content article .`,
      `Cuteblog react adalah sebuah tema dan template yang khusus diperuntukan untuk library react js, dan dengan tema ini tentunya harapan kami selaku pengembang memudahkan mu untuk membuat webiste dan blog dengan cepat. `,
      `Persembahan dari axcora technology untuk dunia agar dapat membuat sebuah website dan blog modern berbasis react dengan konsep blog.`,
    ],
  },
  {
    name: 'gatsby-js',
    title: 'Gatsby JS',
    desc: 'Cuteblog for Gatsby with react JS',
    date: '20 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://media.istockphoto.com/vectors/business-communication-internet-blogging-post-flat-design-vector-vector-id1143088863?k=20&m=1143088863&s=612x612&w=0&h=kJgOoz9QAhbT83Acyhm9whRtxt2j7J7VzWAxCHuEa8o=',
    content: [
      `If you love gatsby js so stay tuned.. next we develope cuteblog to using gatsby js, of course same concept and design with cuteblog.`,
      `Dan ya bagi kamu pencinta gatsby js maka tunggu project kami selanjutnya untuk cuteblog themes template menggunakan gatsby, dan pastinya gratis untuk kamu unduh full source code free download.`,
    ],
  },
  {
    name: 'installation',
    title: 'Install',
    date: '20 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://thumbs.dreamstime.com/b/flat-design-business-process-workflow-management-communicating-ready-to-animation-characters-compouse-your-scenes-office-work-128992317.jpg',
    desc: 'How to install cuteblog react ',
    content: [
      `Oke now how to install this cuteblog  project ?? for first make sure you have installing node on your devices, or you can download and install node first, after this we need to download source code project and code editor too... so for code editor you can download visual code studio and install on your device.`,
      `Oke after installation you need to download cuteblog react source code on or github repo, just github icon click button on navbar. or you can using git bash with run git clone https://github.com/mesinkasir/cuteblogreact.git `,
      `Now extract all source code project and you need to install with run npm install && npm start , then open localhost:3000 , congratulation now you have success installing cuteblog for react on your devices. `,
    ],
  },
  {
    name: 'work',
    title: 'Work',
    date: '20 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://img.freepik.com/free-vector/happy-freelancer-with-computer-home-young-man-sitting-armchair-using-laptop-chatting-online-smiling-vector-illustration-distance-work-online-learning-freelance_74855-8401.jpg?w=2000',
    desc: 'How to work with cuteblog react',
    content: [
      `Oke after you have successfully installed and run on your devices, now you can open source code project using visual code studio, then you can open on src folder , and select ArticleContent.js files - open and edit this files then change with you needed, just follow stucture files for create new article content, and save it for update data.`,
      `For SEO you can visit on index.js file and change title description and other on helmet .`,
    ],
  },
  {
    name: 'deploy',
    title: 'Deploy',
    date: '19 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://img.freepik.com/free-vector/people-putting-puzzle-pieces-together_52683-28610.jpg?w=2000',
    desc: 'How to deploy on static hosting or shared cloud hosting',
    content: [
      `Oke after change and finishin your project , now you need to cloud your source code right, this is for online your website and blog, so for first you can use two option using firebase and surge or use netlify , vercel, heroku etc.`,
      `For using firebase and surge for first you need to build to production mode, so you can input this command on shell terminal npm run build - then you can deploy on public folder to firebase or surge .`,
      `Option two you can use github intergation with heroku,vercel,netlify - just create account and create new repo and push your source code to your repo project, and you need to integration with netlify ,heroku or vercel, just create new project then select your github repo and deploy it. `,
    ],
  },
  {
    name: 'alternative',
    title: 'Alternative',
    date: '18 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://appedology.pk/wp-content/uploads/2020/11/6be369b11b50e0b1c3a2fea19ba7e2ba.png',
    desc: 'Use static site generator with cuteblog',
    content: [
      `If you need to build and develope cuteblog project with static site generator , of course you can do it... we have develope cuteblog for jekyll, eleventy 11ty and astro, just visit on our github repo and search cuteblog with generator static site download it then run and deploy on hosting.`,
      `You can visit on our blog for download all source code project, just visit on https://www.hockeycomputindo.com/2010/12/blog-post.html`,
      `Cuteblog for jekyll is soon.. on progress...`,
      `Cuteblog for eleventy download and read documentation on https://www.hockeycomputindo.com/2022/04/cuteblog-11ty-for-eleventy-generator.html`,
      `Our first Cuteblog project build using astro download and read documentation on https://www.hockeycomputindo.com/2022/04/cute-blog-astro-generator-static-site.html`,
    ],
  },
  {
    name: 'cms',
    title: 'Cuteblog CMS',
    date: '18 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://img.freepik.com/free-vector/group-people-working-together_52683-28615.jpg?w=2000',
    desc: 'If you need build cuteblog with backend admin area so use cuteblog webapp',
    content: [
      `And if you need to work with admin area of course you can do it, yeah.. we have develope cuteblog for content management system to.. so with this cms you can easy for install and deploy or run on your shared cloud hosting, yes.. we have develope using php lang, so you can easy for deploy on your cloud shared hosting.`,
      `Cuteblog pico cms, yes.. we have develope using pico cms, so why use pico ?? of course with pico is very secure and fast , this way why we chose pico, just download and upload it on your hosting then your webiste is live, and you can work with admin area too.. so if you need work using pico cms so download now just visit this link https://axcora.my.id/pico/cuteblog .`,
      `Cuteblog for Get axcora cms - on progress development... yes this is our cms project from get simple, so you can easy download it and upload on hosting, then you can work with admin area and text editor is include , no need database installation, so you can download cuteblog for get axcora on https://axcora.com/getaxcoracms`,
    ],
  },
  {
    name: 'cloud',
    title: 'Cloud with Us',
    date: '16 april 2022',
    author: 'axcora',
    authorlink: 'https://website.axcora.com',
    img: 'https://media.istockphoto.com/vectors/multimedia-content-upload-interface-vector-id1299267805?k=20&m=1299267805&s=612x612&w=0&h=h2TKY77Vcd2144vvjYZbn2eTQr6XoHxDLPMKvI4jU7Q=',
    desc: 'Create and build your modern website with us for best solutions',
    content: [
      `If you need to build and develop modern website using modern technology like static site generator with jekyll, eleventy 11ty , astro or user react, svelte kit, angular so you can use our services with cheap price`,
      `Or you need to create web app where website integration with your point of sale application so we can do it , with multiple technology let's get started build your website application including android app.`,
      `Contact Us`,
      `Whatsapp : +6285646104747`,
      `Call Us : +62895339403223`,
      `Email : axcora@gmail.com`,
    ],
  },
];

export default articles;
